openapi: 3.0.0
info:
  version: '1.5'
  title: LCE Order API
  license:
    name: Apache 2.0
  description: 'Pizza ordering API'
  contact:
    name: Kong
servers:
  - url: 'http://mockbin.org/request'
    description: mockbin
paths:    
  '/v1/order/{id}':
    get:
      summary: Fetches an order
      tags:
        - order 
      x-kong-plugin-rate-limiting:
        enabled: true
        config:
          minute: 5
          limit_by: ip
          policy: local  
      responses:
        '200':
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"         
      description: "Fetch an order"
      parameters:
        - schema:
            type: string
            default: "123"
          name: id
          in: path
          required: true
          description: This is the order id
          example: "123"
components:
  schemas:
    Topping:
      properties:
        side:
          type: string
          enum:
          - L
          - R
          - B
        code:
          type: string
          enum:
          - P
          - S
          - SP
          - M
          - O
          - GP
    Pizza:
      properties:
        description:
          type: string
        size:
          type: string
          enum:
          - S
          - M 
          - L
          - XL
        toppings:
          type: array
          items: 
            $ref: "#/components/schemas/Topping"
    Pizzas:
      type: array
      items:
        $ref: "#/components/schemas/Pizza"
    Order:
      required:
      - id
      - name
      - address
      - city
      - pizzas
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        address2:
          type: string
        city:
          type: string
        pizzas:
          type: Pizzas
    Orders:
      type: array
      items:
        $ref: "#/components/schemas/Order"
